<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
?>
<?php if (count($jobs)): // We only want to render something, if there are items.?>
<table class="pagination-content table table-striped table-bordered table-hover" id="jobs-list">
    <thead>
        <tr>
            <th><?php echo $this->translate('Title of the job')?> / <?php echo $this->translate('Companyname')?></th>
            <th><?php echo $this->translate('Location')?> / <?php echo $this->translate('Date of receipt')?></th>
            <th><?php echo $this->translate('Apply')?></th>
        </tr>
    </thead>
<tbody>
<?php

foreach ($jobs as $job): /* @var \Jobs\Entity\Job $job */

    $org = $job->getOrganization();
    ?>
<tr>
    <td>
        <?php if ($org && $org->getImage() &&  $org->getOrganizationName()): ?>
            <div class="yk-logo-list">
                <img class="yk-logo-sm" src="<?php echo $this->basePath($this->organizationImageCache->getUri($job->organization->image)) ?>">
            </div>
        <?php endif ?>
        <?php $href = $job->getLink() ? $job->getLink() : $this->url('lang/jobs/view', array(), array('query' => array('id' => $job->getId())), true); ?>
        <a href="<?php echo $href ?>" target="_blank"><?php echo strip_tags($job->getTitle())?></a>
        <br/><?php
            if ($org && $org->getOrganizationName() && $org->getOrganizationName()->getName()) {
                echo $org->getOrganizationName()->getName();
            }
        ?>
    </td>
    <td>
        <div><?php echo $job->getLocation()?></div>
        <small>
            <?php
            if ($job->getDatePublishStart()): echo $this->dateFormat($job->getDatePublishStart(), 'short', 'none');
            elseif ($job->getDateCreated()): echo $this->dateFormat($job->getDateCreated(), 'short', 'none');
            endif?>
        </small>
         <?php $typeOfContract = $job->getTemplateValues()->get('types')?:'fulltime' ?>
                            <span class="yk-contract yk-<?php echo $typeOfContract?>">
                                <?php echo $typeOfContract; ?>
                            </span>
    </td>
    <td>
        <?php
            echo $this->applyUrl($job);
        ?>
     </td>
</tr>
<?php endforeach?>
</tbody>
</table>
<?php echo $this->paginationControl($jobs, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/jobboard'));?>
<?php endif ?>