<?php
    $id = $this->element->getEntity()->id;
    $lang = $this->params('lang');

?>
<h3><?php echo $this->translate("Job details")?></h3>
<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-body">
                <iframe style="width:100%; height:800px;" src="<?php echo $this->url('lang/jobs/editTemplate', array('id' => $this->element->getEntity()->id)); ?>"></iframe>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="alert alert-info">
            <?php echo $this->translate("You are using a default template. You are free to create your own template, just contact the developing team for integration")?>
            <div id="template-links">
            <ul >
                <?php foreach( ['default'=>'Default',
                                'classic'=>'Classic',
                                'modern' => 'Modern'] as $key=>$val ): ?>
                <li>
                    <a href="<?php echo $this->url('lang/jobs/template', array('id' => $this->element->getEntity()->id,'template'=>$key))?>">
                        <?php echo $this->translate($val)?>
                    </a>
                </li>
                <?php endforeach;?>

            </ul>
                <?php $this->headScript()->appendFile($this->basePath('/Jobs/js/templates.js')); ?>
                <div id="template-links-loading" style="display: none;">loading</div>
            </div>
        </div>
        <div class="alert alert-info">
            <h4><?php echo $this->translate('Track applications')?></h4>
            <?php echo $this->summaryform($this->element->getForm('atsMode'), 'form-horizontal') ?>
        </div>
        <div class="alert alert-info">
            <h4>Klassifikation</h4>
            <?php echo $this->summaryForm($this->element->getForm('classification'), 'form-horizontal') ?>
        </div>
    </div>
</div>
