<?php
/**
 * YAWIK
 *
 * view sript of the start page for unauthenticated users
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
?>
<?php $this->headTitle($this->translate('Home'))?>
<div class="jumbotron text-center">
    <h1><?php echo $this->translate('Welcome to YAWIK!'); ?></h1>
    <p><?php echo $this->translate("we connect recruiters and applicants");?></p>
    <p><?php echo $this->translate("This is a DEMO. All data are reset once a day (2:00 CET).");?></p>
    <p>This Demo-Skin can be downloaded at: <a href="https://github.com/cbleek/YawikDemoSkin">https://github.com/cbleek/YawikDemoSkin</a></p>
</div>
<div class="row">
    <div class="container col-md-6">
        <aside class="panel panel-info">
            <div class="panel-heading"><?php echo $this->translate("Login as a recruiter")?></div>
            <div class="panel-body ">
                <p><?php echo $this->translate("You can use the existing Account. Log in and take a look to some Test data.")?></p>
                <table class="table table-bordered">
                    <tr>
                        <th><?php echo $this->translate("Role")?></th>
                        <th><?php echo $this->translate("Username")?></th>
                        <th><?php echo $this->translate("Password")?></th>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate("Recruiter")?></td>
                        <td><b>demo</b></td>
                        <td><b>demo</b></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate("Applicant")?></td>
                        <td><b>applicant</b></td>
                        <td><b>applicant</b></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate("Administrator")?></td>
                        <td><b>admin</b></td>
                        <td><b>admin</b></td>
                    </tr>

                </table>
                <form action="<?php echo $this->basePath()?>/<?php echo $this->params('lang') ?>/login?ref=%2F<?php echo $this->params('lang') ?>" method="post" name="login-form" id="login-form" class="form-inline">
                    <fieldset id="credentials">
                        <div class="fieldset-content">
                            <div class="controls controls-row row">
                                <div class="col-md-3 yk-label">
                                    <label for="credentials-login"><?php echo $this->translate("Username")?></label>
                                </div>
                                <div class="col-md-9" id="credentials-login-span">
                                    <input name="credentials[login]" id="credentials-login" class=" form-control " type="text" value="">
                                    <div id="credentials-login-errors"></div>
                                </div>
                            </div>
                            <div class="controls controls-row row">
                                <div class="col-md-3 yk-label">
                                    <label for="credentials-credential"><?php echo $this->translate("Password")?></label>
                                </div>
                                <div class="col-md-9" id="credentials-credential-span">
                                    <input type="password" name="credentials[credential]" id="credentials-credential" class="form-control" value="">
                                    <div id="credentials-credential-errors"></div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <nav class="navbar">
                        <input type="submit" name="buttons[button]" id="submit" class="btn btn-primary" value="<?php echo $this->translate("login")?>">
                        <div id="submit-errors"></div>
                    </nav>
                </form>
            </div>
        </aside>
    </div>

    <div class="container col-md-6">
        <aside class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate("Test application form")?></h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <?php echo $this->translate("Here you can test an application formular")?>.
                        </p>
                        <h2><?php echo sprintf($this->translate('%sapplication form%s.'),
                                '<a href="' . $this->url('lang/apply', array('applyId' => 'sw-devel'), /* reuse matched params*/ true) . '">',
                                '</a>') ?></h2>
                        <p><?php echo $this->translate('Application is handled within the ATS');?></p>

                        <h2><?php echo sprintf($this->translate('%sapplication form%s.'),
                                '<a href="' . $this->url('lang/apply', array('applyId' => 'administrator'), /* reuse matched params*/ true) . '">',
                                '</a>') ?></h2>
                        <p><?php echo $this->translate('Application is send via E-Mail');?></p>
                    </div>
                    <div class="col-md-6 embed-responsive embed-responsive-16by9">
                        <p>See a Demo on Youtube</p>
                        <iframe src="https://www.youtube.com/embed/peoO-RVJM_0" frameborder="0" allowfullscreen></iframe>
                    </div>
                </div>

            </div>
        </aside>
    </div>

    <div class="container col-md-6 pull-right">
        <aside class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate("Create an Account")?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo $this->translate("Login to an open source applicant tracking system using your favorite social network");?>
                    <?php echo $this->translate("But remember, the demo database is reset once a day. Newly created accounts are silently removed at 2:00 CET.");?>
                </p><br>
                <p>
                    <?php $ref = $this->buildReferer(array('logout', 'ref')); ?>
                    <?php foreach (array('facebook' => 'Facebook', 'linkedin' => 'LinkedIn', 'xing' => 'Xing', 'github' => 'Github', 'google' => 'Google' ) as $provider => $name): ?>
                        <a class="btn btn-social btn-<?php echo $provider ?>" title="<?php echo sprintf($this->translate('Login with %s'), $name)?>" href="<?php echo $this->url('auth-provider', array('provider' => $provider), array('query' => array('ref' => urlencode($ref))))?>"><i class="fa fa-<?php echo $provider?>"></i> <?php echo $name?></a>
                    <?php endforeach ?>
                </p><br>
                <p>
                    <?php echo sprintf($this->translate("You can also register to this demo using this %s"),'<a href="'.$this->basePath("/de/auth/register").'">'.$this->translate("registration form")."</a>");?>
                </p>

            </div>
        </aside>
    </div>

    <div class="container col-md-3">
        <aside class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <?php echo $this->translate("Integrate Jobs into your personal homepage");?>
                </h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo sprintf($this->translate("You can add your active job openings into your personal homepage by using the %s"),'<a href="https://github.com/cbleek/YawikWidget">YawikWidget</a>')?>
		    <a href="https://yawik.org/2016/01/einbinden-von-stellenanzeigen-in-die-eigene-homepage/">more informations</a>.
                </p>
            </div>
        </aside>
    </div>


    <div class="container col-md-3">
        <aside class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <?php echo $this->translate("YAWIK as a Jobboard");?>
                </h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo sprintf($this->translate("Take a look at YAWIK running as a %s"),'<a href="http://jobs.yawik.org">'.$this->translate("Jobboard").'</a>. ')?>
		    <?php echo sprintf($this->translate("Here is an example of YAWIK running as a %s"),'<a href="https://mygreatjobs.de/">'.$this->translate("Jobboard for people with roots outside of Germany").'</a>. ')?>
		    <?php echo sprintf($this->translate("Here is an example of YAWIK running as a %s"),'<a href="http://www.jobs-deutschland.de">'.$this->translate("Click&Buy Portal").'</a>. ')?>
                </p>
            </div>
        </aside>
    </div>

</div>
