<?php
/**
 * YAWIK
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2014 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html

$notifications = $this->partial('core/notifications');

// set available languages

$languages = array('en', 'de', 'fr', 'es', 'it', 'nl', 'ru', 'pl', 'tr', 'hi', 'ar', 'pt', 'zh');

// set default page title

$this->headTitle($this->translate('YAWIK DEMO'))->setSeparator(' - ')->setAutoEscape(false);

// set default keywords

$this->headMeta()->setCharset("utf-8");
$this->headMeta()->appendName("keywords", "Open Surce Bewerbermanagement System, Bewerberverwaltung");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

$this->configHeadScript()->setAllowArbitraryAttributes(true);
$this->configHeadScript()->prependFile($this->basepath('Core/js/core.init.js'));
$this->configHeadScript()->prependFile($this->basePath('Core/js/pnotify.custom.min.js'), 'text/javascript');
$this->configHeadScript()->prependFile($this->basePath('js/bootstrap.min.js'));
$this->configHeadScript()->prependFile($this->basePath('js/jquery.min.js'));
$this->configHeadScript()->appendScript('var lang="' . $this->params('lang') . '";'
    . 'var basePath="' . $this->basePath() . '";');

$this->headLink()->prependStylesheet($this->basePath() . '/YawikDemoSkin/YawikDemoSkin.css');
$this->headLink()->prependStylesheet($this->basePath('/Core/css/pnotify.custom.min.css'));

foreach ($languages as $lang) {
    $this->headLink()->appendAlternate(
        preg_replace('~^'.$this->basepath('/'.$this->params('lang')).'~',
            $this->basepath('/'.$lang),$_SERVER['REQUEST_URI']),
        'hreflang',
        $this->headTitle()->setTranslator()->renderTitle() ,
        array('hreflang'=>$lang));
}
?>
<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->configHeadScript() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
</head>
<body>
<a class="sr-only" href="#content">Skip to main content</a>
<header role="banner">
    <div class=" navbar-inverse">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" data-target=".yk-navbar-collapse" data-toggle="collapse"
                    type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand hidden-xs" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">YAWIK DEMO</a>
            <a class="navbar-brand visible-xs" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">Y</a>
        </div>
        <nav id="main-navigation" class="navbar-collapse collapse yk-navbar-collapse" role="navigation">
            <?php
            echo $this->navigation('Core/Navigation')
                ->setAcl($this->services('acl'))
                ->setRole($this->auth('role'))
                ->menu()
                ->setMaxDepth(0) // only show the top level entries
                ->setUlClass('nav navbar-nav pull-left')//renderPartial(null, 'main-navigation')
            ?>
            <?php echo $this->loginInfo() ?>
        </nav>
        <!-- /main-navigation -->
    </div>
</header>
<div class="container col-md-2">
    <!-- SIDEBAR -->
    <nav id="sidebar">
        <div class="btn-group" data-toggle="buttons-radio" id="language-switcher">
            <?php $lang = $this->params('lang');
            foreach ( $languages as $availableLang): ?>
                <button type="button"
                        class="btn btn-xs btn-default<?php echo $availableLang == $lang ? ' active' : '' ?>"
                        id="language-switcher-<?php echo $availableLang ?>">
                    <?php echo strtoupper($availableLang) ?></button>
            <?php endforeach ?>
        </div>
        <p><a href="https://www.transifex.com/projects/p/yawik/">
                <?php echo $this->translate('Help to translate YAWIK'); ?></a></p>

        <div id="sub-nav">
            <?php
            echo $this->navigation()->menu()
                ->setOnlyActiveBranch(true)
                ->setMaxDepth(null)
                ->setMinDepth(1)
                ->setRenderParents(false)
                ->setUlClass('nav nav-pills nav-stacked');
            ?>
            <?php
            /**
             * you can put partials
             */
            foreach ($this->layout()->getChildren() as $child):
                if (0 === strpos($child->captureTo(), "sidebar_")):
                    echo $this->{$child->captureTo()};
                endif;
            endforeach;?>
        </div>
    </nav>
    <!-- /SIDEBAR -->
</div>

<main id="content" class="col-md-10">
    <?php echo $notifications?>
    <?php echo $this->content; ?>
</main>
<!-- /container -->
<footer id="yk-footer">
 <div class="container">
    <div class="row">
           <div class="col-md-4">
               <small>
                   <a href="http://www.jetbrains.com/phpstorm/"
                      style="position: relative;display:block; float:left; width:230px; height:33px; border:0; margin:0;padding:0;text-decoration:none;text-indent:0;"><span
                           style="margin: 0;padding: 0;position: absolute;top: 10px;left:4px;font-size: 11px;cursor:pointer;  background-image:none;border:0;color: #5854b5;font-family: trebuchet ms,arial,sans-serif;font-weight: normal;text-align:left;">Developed with</span><img
                           src="https://www.jetbrains.com/phpstorm/documentation/phpstorm_banners/phpstorm1/phpstorm230x33_white.gif"
                           alt="Developed with" border="0"/></a>
               </small>
           </div>
	   <div class="col-md-4"><center>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="LB3Q3ES348HHG">
<input type="image" src="https://www.paypalobjects.com/en_US/DE/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/de_DE/i/scr/pixel.gif" width="1" height="1">
</form></center>
           </div>
           <div class="col-md-4" align="right">
                <span class="pull-right"><small>
                        &copy; 2013-<?php echo date("Y")?> <a href="http://cross-solution.de">
                            Cross
                            Solution</a>. <?php echo $this->translate('All rights reserved.') ?>
                        | <?php passthru('git describe') ?> [<?php passthru('git rev-parse --abbrev-ref HEAD') ?>]<br/>
                        Powered by <a href="http://yawik.org">YAWIK</a>
                 </small></span>
           </div>
    </div>
  </div>
</footer>
<?php echo $this->partial("piwik") ?>
</body>
</html>
