<?php
/**
 * YAWIK
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

/* @var $options \Core\Options\ModuleOptions */
$options = $this->services('Core/Options');
$languages = $options->getSupportedLanguages();
$lang = $this->params('lang');


// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html

$notifications = $this->partial('core/notifications');

// set default page title

$this->headTitle($this->translate('YAWIK DEMO'))->setSeparator(' - ')->setAutoEscape(false);

// set default keywords

$this->headMeta()->setCharset("utf-8");
$this->headMeta()->appendName("keywords", "Open Surce Bewerbermanagement System, Bewerberverwaltung");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

$this->configHeadScript()->setAllowArbitraryAttributes(true);

$this->configHeadScript()->prependFile($this->basepath('dist/js/core.js'));

$this->configHeadScript()->appendScript('var lang="' . $this->params('lang') . '";'
    . 'var basePath="' . $this->basePath() . '";');


if (getenv('CORE_CSS') && !empty(getenv('CORE_CSS'))) {
  $this->headLink()->prependStylesheet(getenv('CORE_CSS'));
}else{
  $this->headLink()->prependStylesheet($this->basePath('modules/YawikDemoSkin/dist/YawikDemoSkin.css'));
}

foreach ($languages as $lang) {
    $this->headLink()->appendAlternate(
        preg_replace('~^'.$this->basepath('/'.$this->params('lang')).'~',
            $this->basepath('/'.$lang),$_SERVER['REQUEST_URI']),
        'hreflang',
        $this->headTitle()->setTranslator()->renderTitle() ,
        array('hreflang'=>$lang));
}
?>
<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->configHeadScript() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <link rel="icon" href="<?=$this->basePath('modules/YawikDemoSkin/img/favicon-32x32.jpg')?>" sizes="32x32" />
    <link rel="icon" href="<?=$this->basePath('modules/YawikDemoSkin/img/cropped-yawik-small-192x192.png')?>" sizes="192x192" />
    <link rel="apple-touch-icon-precomposed" href="<?=$this->basePath('modules/YawikDemoSkin/img/apple-icon-180x180.png')?>" />
    <meta name="msapplication-TileImage" content="<?=$this->basePath('modules/YawikDemoSkin/img/cropped-yawik-small-384x384.png')?>" />
</head>
<body>
<a class="sr-only" href="#content">Skip to main content</a>
<header role="banner">
    <div class=" navbar-inverse">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" data-target=".navbar-collapse" data-toggle="collapse"
                    type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand hidden-xs" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">YAWIK DEMO</a>
            <a class="navbar-brand visible-xs" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">Y</a>
        </div>
        <nav id="main-navigation" class="navbar-collapse collapse navbar-collapse" role="navigation">
            <?php
            echo $this->navigation('Core/Navigation')
                ->setAcl($this->services('acl'))
                ->setRole($this->auth('role'))
                ->menu()
                ->setMaxDepth(0) // only show the top level entries
                ->setUlClass('nav navbar-nav pull-left')//renderPartial(null, 'main-navigation')
            ?>
            <?php echo $this->loginInfo() ?>
        </nav>
        <!-- /main-navigation -->
    </div>
</header>
<div class="container col-md-2">
    <!-- SIDEBAR -->
    <nav id="sidebar">
       <?=$this->languageSwitcher()?>
        <p><a href="https://www.transifex.com/projects/p/yawik/">
                <?php echo $this->translate('Help to translate YAWIK'); ?></a></p>

        <div id="sub-nav">
            <?php
            echo $this->navigation()->menu()
                ->setOnlyActiveBranch(true)
                ->setMaxDepth(null)
                ->setMinDepth(1)
                ->setRenderParents(false)
                ->setUlClass('nav nav-pills nav-stacked');
            ?>
            <?php
            /**
             * you can put partials
             */
            foreach ($this->layout()->getChildren() as $child):
                if (0 === strpos($child->captureTo(), "sidebar_")):
                    echo $this->{$child->captureTo()}?:$this->render($child);
                endif;
            endforeach;?>
        </div>
    </nav>
    <!-- /SIDEBAR -->
</div>

<main id="content" class="col-md-10">
    <?php echo $notifications?>
    <?php echo $this->content; ?>
</main>
<!-- /container -->
<footer id="yk-footer">
 <div class="container">
    <div class="row">
           <div class="col-md-4">
               <small>
                   <a href="http://www.jetbrains.com/phpstorm/">
                       <img src="<?php echo $this->basePath('modules/YawikDemoSkin/img/logo_PhpStorm.svg')?>"
                           alt="Developed with PhpStorm" border="0" style="height: 30px"/></a>
               </small>
           </div>
	   <div class="col-md-4"><center>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="LB3Q3ES348HHG">
<input type="image" src="https://www.paypalobjects.com/en_US/DE/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/de_DE/i/scr/pixel.gif" width="1" height="1">
</form></center>
           </div>
           <div class="col-md-4" align="right">
                <span class="pull-right"><small>
                        &copy; 2013-<?php echo date("Y")?> <a href="http://cross-solution.de">
                            Cross
                            Solution</a>.
                        | <a href="<?php echo  $this->basePath($this->params('lang').'/content/imprint')?>"><?php echo $this->translate('Imprint') ?></a>
                        | <?php echo $this->moduleVersion('YawikDemoSkin')->full() ?><br/>
                        Powered by <a href="http://yawik.org">YAWIK</a> <?=$this->moduleVersion('Core') ?>
                 </small></span>
           </div>
    </div>
  </div>
</footer>
<?php echo $this->partial("piwik") ?>
</body>
</html>
