<?php

/**
 * YAWIK
 *
 * @filesource
 * @author    Carsten Bleek <bleek@cross-solution.de>
 * @copyright 2013-2017 Cross Solution (http://cross-solution.de)
 * @version   GIT: $Id$
 * @license   https://yawik.org/LICENSE.txt MIT
 */

?>

<div class="panel panel-default">
    <div class="panel-heading">This demo uses the following additional YAWIK modules</div>
    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item"><a href="https://github.com/yawik/DemoSkin">YawikDemoSkin</a></li>
            <li class="list-group-item"><a href="http://yawik.readthedocs.io/en/latest/modules/solr/index.html">Solr</a></li>
            <li class="list-group-item"><a href="http://yawik.readthedocs.io/en/latest/modules/orders/index.html">Orders</li>
            <li class="list-group-item"><a href="http://yawik.readthedocs.io/en/latest/modules/jobs-by-mail/index.html">JobsByMail</a></li>
        </ul>
    </div>
</div>

